#pragma once

#include "always.hpp"
#include "apply.hpp"
#include "arg.hpp"
#include "capture.hpp"
#include "compose.hpp"
#include "curry.hpp"
#include "demux.hpp"
#include "fix_point.hpp"
#include "flip.hpp"
#include "identity.hpp"
#include "iterate.hpp"
#include "lockstep.hpp"
#include "partial.hpp"
#include "reverse_partial.hpp"
