stages:
    - build
    - doc

.job-basic-build-linux: &distcheck-basic-linux
    stage: build
    image: mroynard/ubuntu-toolset
    variables:
      BUILD_DIR: "build-in-docker"
      BUILD_ALL: "ON"
      CMAKE_GENERATOR: "Ninja"
      DEFAULT_TARGET: "check"
    script:
        /usr/local/bin/build-dispatch -v -b $BUILD_DIR -g $CMAKE_GENERATOR -c $COMPILER -t $DEFAULT_TARGET -r $RELEASE_TYPE -- -DWITH_EXAMPLES=$BUILD_ALL -DWITH_BENCHMARK=$BUILD_ALL

distcheck-linux-gcc-release:
    <<: *distcheck-basic-linux
    variables:
        RELEASE_TYPE: "Release"
        COMPILER: "gcc"

distcheck-linux-clang-release:
    <<: *distcheck-basic-linux
    variables:
        RELEASE_TYPE: "Release"
        COMPILER: "clang"

distcheck-linux-gcc-debug:
    <<: *distcheck-basic-linux
    variables:
        RELEASE_TYPE: "Debug"
        COMPILER: "gcc"

distcheck-linux-clang-debug:
    <<: *distcheck-basic-linux
    variables:
        RELEASE_TYPE: "Debug"
        COMPILER: "clang"

documentation-builder
    stage: doc
    image: mroynard/ubuntu-toolset
    variables:
        BUILD_DIR: "build-in-docker"
        CMAKE_GENERATOR: "Ninja"
        DEFAULT_TARGET: "check"
    script:
        /usr/local/bin/build-dispatch -v -g $CMAKE_GENERATOR -t $check -b $BUILD_DIR
    artifacts:
        name: "documentation"
        paths:
            - $BUILD_DIR/doc/api
            - $BUILD_DIR/doc/user
