variables:
    BUILD_DIR: "build-in-docker"
    BUILD_AND_RUN_EXAMPLES: "ON"
    BUILD_AND_RUN_BENCHMARKS: "ON"
    CMAKE_GENERATOR: "Ninja"
    DEFAULT_TARGET: "check"

stages:
    - build
    - doc

.job-basic-build-linux: &distcheck-basic-linux
    stage: build
    image: mroynard/ubuntu-toolset
    script:
        /usr/local/bin/build-dispatch \
          --verbose \
          --coverage \
          --cmake-generator $CMAKE_GENERATOR \
          --build-directory $BUILD_DIR \
          --compiler $COMPILER \
          --targett $DEFAULT_TARGET \
          --release-type $RELEASE_TYPE \
          -- -DWITH_EXAMPLES=$BUILD_AND_RUN_EXAMPLES -DWITH_BENCHMARK=$BUILD_AND_RUN_BENCHMARKS

distcheck-linux-gcc-release:
    <<: *distcheck-basic-linux
    variables:
        RELEASE_TYPE: "Release"
        COMPILER: "gcc"

distcheck-linux-clang-release:
    <<: *distcheck-basic-linux
    variables:
        RELEASE_TYPE: "Release"
        COMPILER: "clang"

distcheck-linux-gcc-debug:
    <<: *distcheck-basic-linux
    variables:
        RELEASE_TYPE: "Debug"
        COMPILER: "gcc"

distcheck-linux-clang-debug:
    <<: *distcheck-basic-linux
    variables:
        RELEASE_TYPE: "Debug"
        COMPILER: "clang"

documentation-builder:
    stage: doc
    image: mroynard/ubuntu-toolset
    variables:
        DEFAULT_TARGET: "docs"
    script:
        /usr/local/bin/build-dispatch \
          --verbose \
          --cmake-generator $CMAKE_GENERATOR \
          --target $DEFAULT_TARGET \
          --build-directory $BUILD_DIR
    artifacts:
        name: "documentation"
        paths:
            - $BUILD_DIR/doc/api
            - $BUILD_DIR/doc/user
        expire_in: 14 days
