variables:
    BUILD_DIR: "build-in-docker"
    SOURCE_DIR: ".."
    BUILD_AND_RUN_EXAMPLES: "ON"
    BUILD_AND_RUN_BENCHMARKS: "ON"
    BUILD_WITH_CODE_COVERAGE: "OFF"
    FORCE_REBUILD: "OFF"
    VERBOSE: "ON"
    CMAKE_GENERATOR: "Ninja"
    CMAKE_TOOLCHAIN_ARGS: "" # can be -j4 for unix makefiles
    DEFAULT_TARGET: "check"

stages:
    - build
    - doc

.job-basic-build-linux: &distcheck-basic-linux
    stage: build
    image: mroynard/ubuntu-toolset:stable
    script:
      - set -e
      - export CC=$CC
      - export CXX=$CXX
      - $CXX --version
      - mkdir -p $BUILD_DIR
      - cd $BUILD_DIR
      - if [ "$FORCE_REBUILD" == "ON" ]; then rm -rf ./*; fi
      - if [ "$VERBOSE" == "ON" ]; then set -x; fi
      - cmake -G $CMAKE_GENERATOR
              -DWITH_CODE_COVERAGE=$BUILD_WITH_CODE_COVERAGE
              -DWITH_EXAMPLES=$BUILD_AND_RUN_EXAMPLES
              -DWITH_BENCHMARK=$BUILD_AND_RUN_BENCHMARKS
              $SOURCE_DIR
      - cmake --build .
              --target $DEFAULT_TARGET
              --config $RELEASE_TYPE
              -- $TOOLCHAIN_ARGS

distcheck-linux-gcc-release:
    <<: *distcheck-basic-linux
    variables:
        RELEASE_TYPE: "Release"
        CC: "gcc"
        CXX: "g++"

distcheck-linux-clang-release:
    <<: *distcheck-basic-linux
    variables:
        RELEASE_TYPE: "Release"
        CC: "clang"
        CXX: "clang++"

distcheck-linux-gcc-debug:
    <<: *distcheck-basic-linux
    variables:
        RELEASE_TYPE: "Debug"
        CC: "gcc"
        CXX: "g++"

distcheck-linux-clang-debug:
    <<: *distcheck-basic-linux
    variables:
        RELEASE_TYPE: "Debug"
        CC: "clang"
        CXX: "clang++"

documentation-builder:
    stage: doc
    image: mroynard/ubuntu-doctoolset:stable
    variables:
        DEFAULT_TARGET: "docs"
    script:
      - mkdir build
      - cd build
      - if [ "$VERBOSE" == "ON" ]; then set -x; fi
      - cmake -G $CMAKE_GENERATOR $SOURCE_DIR
      - cmake --build . --target $DEFAULT_TARGET
    artifacts:
        name: "documentation"
        paths:
            - $BUILD_DIR/doc/api
            - $BUILD_DIR/doc/user
        expire_in: 14 days
